---
abstract: 'Simple and fast hash to XML conversion'
author:
  - 'Yuriy Ustushenko <yoreek@yahoo.com>'
build_requires:
  ExtUtils::MakeMaker: 0
configure_requires:
  ExtUtils::MakeMaker: 0
dynamic_config: 1
generated_by: 'ExtUtils::MakeMaker version 6.62, CPAN::Meta::Converter version 2.113640'
license: perl
meta-spec:
  url: http://module-build.sourceforge.net/META-spec-v1.4.html
  version: 1.4
name: XML-Hash-XS
no_index:
  directory:
    - t
    - inc
requires:
  Test::More: 0
version: 0.08
